name: Hook Slinger Build & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run the Linters, Build the Containers & Run the Tests
        run: |
          pip install docker-compose
          make start_tests

      - name: Check Running Containers
          run: docker ps -a

      - name: Check Test
          run: docker logs -f hook-slinger_test_1
